export { default as Search } from './Search'
export { default as NavBar } from './NavBar'
export { default as Slide } from './Slide'
export { default as IconBadge } from './IconBadge'
export { default as CaraouselBrain } from './CarouselBrain'
export { default as CardProduct } from './CardProduct'