export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'

export const FETCH_PRODUCT = 'FETCH_PRODUCT'
export const ADD_PRODUCT = 'ADD_PRODUCT'
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS'

export const ADD_ORDER = 'ADD_ORDER'
export const PLUS_PRODUCT = 'PLUS_PRODUCT'
export const MIN_PRODUCT = 'MIN_PRODUCT'
export const DELETE_ORDER = 'DELETE_ORDER'
export const SUBMIT_ORDER = 'SUBMIT_ORDER'