export {default as slide1} from './slide1.png'
export {default as slide2} from './slide2.png'
export {default as slide3} from './slide3.png'
export {default as slide4} from './slide4.png'
export {default as slide5} from './slide5.png'
export {default as slide6} from './slide6.png'